require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Layout/EndOfLine:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/Documentation:
  Enabled: false
